### PR TITLE
Add support to py35

### PR DESCRIPTION
**Pull request by hugonicodemos**

### CODE REVIEW

**Comment by ricardoas** [comment]
Fix #1

**Comment by ricardoas** [comment]
@LumbaJack would you mind considering this pull request? It is fundamental to the new version of our tools available at https://github.com/HewlettPackard/ironic-driver-oneview

**Comment by LumbaJack** [comment]
Under review.

**Comment by hugonicodemos** [comment]
Thanks, @LumbaJack. Waiting for an answer.

**Comment by LumbaJack** [comment]
Passed testing under linux. Will approve but will need further testing for windows support.

**Pull request merged**
